baseURL = "https://wizfi.github.io/mydocs/"
languageCode = "en-US"
defaultContentLanguage = "en"
hasCJKLanguage = true
summaryLength = 70

title = "WizFi Home"
theme = "hugo-theme-learn"
#themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
enableRobotsTXT = true
#disqusShortname = "ghdevbj"

[taxonomies]
  category = "categories"
  tag = "tags"
  subcategory = "subcategories"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  editURL = "https://github.com/wizfi/mydocs/edit/master/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "WizFi"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/wizfi/mydocs"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 31
